### ISSUE TITLE
Добавить редактирование заказа

### ISSUE THREAD

**Issue by greenmassa** [almaty-attractor-js-first/esdp_js_01#41]
#### Конечный результат: 
Есть возможность вносить изменения в заказы

#### План решения:
Добавить метод в объект бд для изменения данных о заказе 

#### Мотивация: 
Требование в ТЗ

#### Критерии приёмки:
По PUT запросу на '/orders/:id' - измененные поля в заказе переписываются на новые

#### Планируемое время работы:
30 мин

**Comment by vglebov** [comment]
@greenmassa А почему тикет не оформлен?
