### ISSUE TITLE
Реализовать страницу для мастера на фронте на отдельном URL, а также action'ы для отправки на бэк

### ISSUE THREAD

**Issue by greenmassa** [almaty-attractor-js-first/esdp_js_01#42]
### Реализовать страницу для мастера на фронте на отдельном URL, а также action'ы для отправки на бэк

**Конечный результат:**

Страница с отображением детали заказа 

**План решения:**

Создать страницу с деталями о заказе
Отобразить всю необходимую информацию (имя , фамилию Клиента , телефон , email и т.д)

**Мотивация:**

Требование ТЗ

**Критерии приёмки:**

Сценарий gherkin: #73
Функция: Проверка юзкейсов админа
Сценарий: Открытие информации о заказе
Допустим Я нахожусь на странице списка заказов для админа
И Я копирую "имя клиента" из поля 0 нажимаю на поле 0 вижу "имя клиента"
То Я вижу "Информация о заказе"

**Планируемое время работы:**

3 часа

**Comment by vglebov** [comment]
@greenmassa Почему  не оформлен тикет?

**Comment by vglebov** [comment]
@aidosmen Оформи тикет

**Comment by aidosmen** [comment]
> @aidosmen Оформи тикет

оформил
