### ISSUE TITLE
Исследовать "черные ящики" email-уведомлений и генерации QR кода

### ISSUE THREAD

**Issue by greenmassa** [almaty-attractor-js-first/esdp_js_01#43]
#### Конечный результат: 
Понимание того как генерировать QR код и отпралять email уведомления 

#### План решения:
Изучить готовые решения и библиотеки из npm

#### Мотивация: 
Сэкономить время для всей команды

#### Критерии приёмки:
Описание решения с примером в коде

#### Планируемое время работы:
3 часа

**Comment by vglebov** [comment]
@greenmassa оформи тикет
